name = "Hydra Client"
author = "Old School Minecraft"
version = "1.2.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "518ec6ae471613247f02549e6163f1b731554e5f7a28cf15207c24624cb90238"

[versions]
minecraft = "b1.7.3"
